### ISSUE TITLE
`add hotp` raises unhandled exception on missing `-c, --counter` option

### ISSUE THREAD

**Issue by Toreno96** [apptension/onetimepass#33]
```
$ pdm run otp add hotp -h
Usage: otp add hotp [OPTIONS] ALIAS

  Add the new HOTP secret as the specified ALIAS.

Options:
  -c, --counter INTEGER
  -l, --label TEXT
  -i, --issuer TEXT
  -a, --algorithm [sha1|sha256|sha512]
                                  [default: sha1]
  -d, --digits-count INTEGER      [default: 6]
  -h, --help                      Show this message and exit.
$ pdm run otp add hotp foo
Enter secret:
Repeat for confirmation:
Traceback (most recent call last):
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/bin/otp", line 8, in <module>
    sys.exit(otp())
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dstasczak/development/projects/onetimepass/onetimepass/otp.py", line 414, in _wrapped
    return fn(*args, **kwargs)
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dstasczak/development/projects/onetimepass/onetimepass/otp.py", line 452, in add_hotp
    params=HOTPParams(counter=counter),
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for HOTPParams
counter
  none is not an allowed value (type=type_error.none.not_allowed)
```

We should either support the default value (e.g. `-c 0`) or reimplement this as the command argument (`otp add hotp [OPTIONS] ALIAS COUNTER`).

**Comment by Toreno96** [comment]
I went through the [RFC 4226](https://datatracker.ietf.org/doc/html/rfc4226) to find if there's any recommendation for the default counter value and while there's no such recommendation mentioned _explicitly_, it seems they always use `0` in the examples. It could be a sane default.

Although I'm not 100% sure, considering the Key URI [always requires the counter parameter](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#counter), there's no default supported.

**Comment by Toreno96** [comment]
> Although I'm not 100% sure, considering the Key URI [always requires the counter parameter](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#counter), there's no default supported.

I just checked that if you choose to input the HOTP manually into the Google Authenticator, it _won't_ ask about the counter, only the secret. So not only does the counter default to `0`, the user cannot really change that.

In that case, +1 for this approach:
> We should either support the default value (e.g. `-c 0`)

as this preserves the default behavior from the Google Authenticator, and at the same time, extends it (by giving the user the control).

Also, I believe `otp add hotp alias --counter 0 ` is _much_ more clear than `otp add hotp alias 0`.
